apiVersion: v1
kind: Service
metadata:
  name: grapevine-classification-service
spec:
  selector:
    app: grapevine-classification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9696
  type: LoadBalancer

